USE onlineapp;

INSERT IGNORE INTO users VALUES (1, 'test', 'test', '12345', '101 1988 2983',  '个人', 'hawk', '1111 1111 1111', '中国工商银行', 5, 39, '新街口支行', '6995 8808 3728', '/path/id-front', '/path/id-back', '2013-09-07','2010-09-07', 1, 1);

INSERT IGNORE INTO applications VALUES (1, 'TEST_DIANJOY_APP_ID', 'petpet','ios','com.app.me','APP_ID\u5BA1\u6279\u4E2D', '2010-09-07','2010-09-07', 1, 1);

INSERT IGNORE INTO app_parameters VALUES (1, 1, 'chet', 'false', '2012-09-07','2210-09-07', 1, 1);

INSERT IGNORE INTO bonus VALUES (1, 100, '开发者注册送50', '2013-09-07','2010-09-07', 1, 1);

INSERT IGNORE INTO checks VALUES (1, 'glen', '1111 111', 'city bank', 'china bj wangfujing street', '1115 1230 1897 2222', 10000.00, 'passed', '2013-09-07','2010-09-07', 1, 1);

INSERT IGNORE INTO sdks VALUES (1, 'IOS', '积分墙', 'V8.8.8.8', '/path_to_download', '下载联盟工厂积分墙SDK');

INSERT IGNORE INTO dictionary VALUES(1, 'province', null, '北京市') ;
INSERT IGNORE INTO dictionary VALUES(2, 'province', null, '天津市');
INSERT IGNORE INTO dictionary VALUES(3, 'province', null, '上海市') ;
INSERT IGNORE INTO dictionary VALUES(4, 'province', null, '重庆市') ;
INSERT IGNORE INTO dictionary VALUES(5, 'province', null, '河北省') ;
INSERT IGNORE INTO dictionary VALUES(6, 'province', null, '山西省') ;
INSERT IGNORE INTO dictionary VALUES(7, 'province', null, '台湾省') ;
INSERT IGNORE INTO dictionary VALUES(8, 'province', null, '辽宁省') ;
INSERT IGNORE INTO dictionary VALUES(9, 'province', null, '吉林省') ;
INSERT IGNORE INTO dictionary VALUES(10, 'province', null, '黑龙江省') ;
INSERT IGNORE INTO dictionary VALUES(11, 'province', null, '江苏省') ;
INSERT IGNORE INTO dictionary VALUES(12, 'province', null, '浙江省') ;
INSERT IGNORE INTO dictionary VALUES(13, 'province', null, '安徽省') ;
INSERT IGNORE INTO dictionary VALUES(14, 'province', null, '福建省') ;
INSERT IGNORE INTO dictionary VALUES(15, 'province', null, '江西省') ;
INSERT IGNORE INTO dictionary VALUES(16, 'province', null, '山东省') ;
INSERT IGNORE INTO dictionary VALUES(17, 'province', null, '河南省') ;
INSERT IGNORE INTO dictionary VALUES(18, 'province', null, '湖北省') ;
INSERT IGNORE INTO dictionary VALUES(19, 'province', null, '湖南省') ;
INSERT IGNORE INTO dictionary VALUES(20, 'province', null, '广东省') ;
INSERT IGNORE INTO dictionary VALUES(21, 'province', null, '甘肃省') ;
INSERT IGNORE INTO dictionary VALUES(22, 'province', null, '四川省');
INSERT IGNORE INTO dictionary VALUES(23, 'province', null, '贵州省') ;
INSERT IGNORE INTO dictionary VALUES(24, 'province', null, '海南省') ;
INSERT IGNORE INTO dictionary VALUES(25, 'province', null, '云南省') ;
INSERT IGNORE INTO dictionary VALUES(26, 'province', null, '青海省') ;
INSERT IGNORE INTO dictionary VALUES(27, 'province', null, '陕西省') ;
INSERT IGNORE INTO dictionary VALUES(28, 'province', null, '广西壮族自治区');
INSERT IGNORE INTO dictionary VALUES(29, 'province', null, '西藏自治区') ;
INSERT IGNORE INTO dictionary VALUES(30, 'province', null, '宁夏回族自治区') ;
INSERT IGNORE INTO dictionary VALUES(31, 'province', null, '新疆维吾尔自治区') ;
INSERT IGNORE INTO dictionary VALUES(32, 'province', null, '内蒙古自治区') ;
INSERT IGNORE INTO dictionary VALUES(33, 'province', null, '澳门特别行政区') ;
INSERT IGNORE INTO dictionary VALUES(34, 'province', null, '香港特别行政区') ;

##插入各个省的dictionary 数据 ##4个直辖市 ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(35, 'city', '北京市',1) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(36, 'city', '天津市',2) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(37, 'city', '上海市',3) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(38, 'city', '重庆市',4) ;
##5河北省(2005年辖：11个地级市，36个市辖区、22个县级市、108个县、6个自治县) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(39, 'city', '石家庄市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(40, 'city', '唐山市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(41, 'city', '秦皇岛市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(42, 'city', '邯郸市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(43, 'city', '邢台市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(44, 'city', '保定市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(45, 'city', '张家口市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(46, 'city', '承德市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(47, 'city', '沧州市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(48, 'city', '廊坊市',5) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(49, 'city', '衡水市',5) ;
##6山西省11个dictionary  ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(51, 'city', '太原市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(52, 'city', '大同市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(53, 'city', '阳泉市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(54, 'city', '长治市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(55, 'city', '晋城市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(56, 'city', '朔州市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(57, 'city', '晋中市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(58, 'city', '运城市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(59, 'city', '忻州市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(60, 'city', '临汾市',6) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(61, 'city', '吕梁市',6) ;
##7台湾省(台湾本岛和澎湖共设7市、16县，其中台北市和高雄市为“院辖市”，直属“行政院”，其余属台湾省；市下设区，县下设市（县辖市）、镇、乡，合称区市镇乡。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(71, 'city', '台北市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(72, 'city', '高雄市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(73, 'city', '基隆市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(74, 'city', '台中市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(75, 'city', '台南市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(76, 'city', '新竹市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(77, 'city', '嘉义市',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(78, 'city', '台北县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(79, 'city', '宜兰县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(80, 'city', '桃园县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(81, 'city', '新竹县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(82, 'city', '苗栗县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(83, 'city', '台中县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(84, 'city', '彰化县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(85, 'city', '南投县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(86, 'city', '云林县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(87, 'city', '嘉义县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(88, 'city', '台南县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(89, 'city', '高雄县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(90, 'city', '屏东县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(91, 'city', '澎湖县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(92, 'city', '台东县',7) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(93, 'city', '花莲县',7) ;
##8辽宁省(2006年，辖：14个地级市；56个市辖区、17个县级市、19个县、8个自治县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(101, 'city', '沈阳市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(102, 'city', '大连市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(103, 'city', '鞍山市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(104, 'city', '抚顺市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(105, 'city', '本溪市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(106, 'city', '丹东市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(107, 'city', '锦州市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(108, 'city', '营口市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(109, 'city', '阜新市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(110, 'city', '辽阳市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(111, 'city', '盘锦市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(112, 'city', '铁岭市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(113, 'city', '朝阳市',8) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(114, 'city', '葫芦岛市',8) ;
##9吉林省(2006年，辖：8个地级市、1个自治州；20个市辖区、20个县级市、17个县、3个自治县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(121, 'city', '长春市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(122, 'city', '吉林市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(123, 'city', '四平市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(124, 'city', '辽源市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(125, 'city', '通化市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(126, 'city', '白山市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(127, 'city', '松原市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(128, 'city', '白城市',9) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(129, 'city', '延边朝鲜族自治州',9);
##10黑龙江省(2006年，辖：12地级市、1地区；64市辖区、18县级市、45县、1自治县) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(131, 'city', '哈尔滨市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(132, 'city', '齐齐哈尔市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(133, 'city', '鹤 岗 市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(134, 'city', '双鸭山市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(135, 'city', '鸡 西 市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(136, 'city', '大 庆 市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(137, 'city', '伊 春 市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(138, 'city', '牡丹江市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(139, 'city', '佳木斯市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(140, 'city', '七台河市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(141, 'city', '黑 河 市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(142, 'city', '绥 化 市',10) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(143, 'city', '大兴安岭地区',10) ;
##11江苏省(2005年辖：13个地级市；54个市辖区、27个县级市、25个县) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(151, 'city', '南京市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(152, 'city', '无锡市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(153, 'city', '徐州市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(154, 'city', '常州市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(155, 'city', '苏州市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(156, 'city', '南通市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(157, 'city', '连云港市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(158, 'city', '淮安市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(159, 'city', '盐城市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(160, 'city', '扬州市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(161, 'city', '镇江市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(162, 'city', '泰州市',11) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(163, 'city', '宿迁市',11) ;
##12浙江省(2006年，辖：11个地级市；32个市辖区、22个县级市、35个县、1个自治县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(171, 'city', '杭州市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(172, 'city', '宁波市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(173, 'city', '温州市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(174, 'city', '嘉兴市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(175, 'city', '湖州市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(176, 'city', '绍兴市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(177, 'city', '金华市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(178, 'city', '衢州市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(179, 'city', '舟山市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(180, 'city', '台州市',12) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(181, 'city', '丽水市',12) ;
##13安徽省(2005年辖：17个地级市；44个市辖区、5县个级市、56个县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(191, 'city', '合肥市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(192, 'city', '芜湖市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(193, 'city', '蚌埠市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(194, 'city', '淮南市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(195, 'city', '马鞍山市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(196, 'city', '淮北市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(197, 'city', '铜陵市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(198, 'city', '安庆市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(199, 'city', '黄山市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(200, 'city', '滁州市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(201, 'city', '阜阳市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(202, 'city', '宿州市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(203, 'city', '巢湖市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(204, 'city', '六安市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(205, 'city', '亳州市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(206, 'city', '池州市',13) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(207, 'city', '宣城市',13) ;
##14福建省(2006年辖：9个地级市；26个市辖区、14个县级市、45个县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(211, 'city', '福州市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(212, 'city', '厦门市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(213, 'city', '莆田市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(214, 'city', '三明市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(215, 'city', '泉州市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(216, 'city', '漳州市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(217, 'city', '南平市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(218, 'city', '龙岩市',14) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(219, 'city', '宁德市',14) ;
##15江西省(2006年全省辖：11个地级市；19个市辖区、10个县级市、70个县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(221, 'city', '南昌市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(222, 'city', '景德镇市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(223, 'city', '萍乡市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(224, 'city', '九江市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(225, 'city', '新余市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(226, 'city', '鹰潭市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(227, 'city', '赣州市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(228, 'city', '吉安市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(229, 'city', '宜春市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(230, 'city', '抚州市',15) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(231, 'city', '上饶市',15) ;
##16山东省(2005年，辖：17个地级市；49个市辖区、31个县级市、60个县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(241, 'city', '济南市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(242, 'city', '青岛市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(243, 'city', '淄博市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(244, 'city', '枣庄市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(245, 'city', '东营市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(246, 'city', '烟台市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(247, 'city', '潍坊市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(248, 'city', '济宁市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(249, 'city', '泰安市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(250, 'city', '威海市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(251, 'city', '日照市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(252, 'city', '莱芜市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(253, 'city', '临沂市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(254, 'city', '德州市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(255, 'city', '聊城市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(256, 'city', '滨州市',16) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(257, 'city', '菏泽市',16) ;
##17河南省（2005年辖：17个地级市；50个市辖区、21个县级市、88个县。）;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(261, 'city', '郑州市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(262, 'city', '开封市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(263, 'city', '洛阳市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(264, 'city', '平顶山市',17);
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(265, 'city', '安阳市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(266, 'city', '鹤壁市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(267, 'city', '新乡市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(268, 'city', '焦作市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(269, 'city', '濮阳市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(270, 'city', '许昌市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(271, 'city', '漯河市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(272, 'city', '三门峡市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(273, 'city', '南阳市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(274, 'city', '商丘市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(275, 'city', '信阳市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(276, 'city', '周口市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(277, 'city', '驻马店市',17) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(278, 'city', '济源市',17) ;
##18湖北省（截至2005年12月31日，全省辖13个地级单位（12个地级市、1个自治州）；102县级单位（38个市辖区、24个县级市、37个县、2个自治县、1个林区），共有1220个乡级单位（277个街道、733个镇、210个乡）。） ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(281, 'city', '武汉市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(282, 'city', '黄石市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(283, 'city', '十堰市',18);
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(284, 'city', '荆州市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(285, 'city', '宜昌市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(286, 'city', '襄樊市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(287, 'city', '鄂州市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(288, 'city', '荆门市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(289, 'city', '孝感市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(290, 'city', '黄冈市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(291, 'city', '咸宁市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(292, 'city', '随州市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(293, 'city', '仙桃市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(294, 'city', '天门市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(295, 'city', '潜江市',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(296, 'city', '神农架林区',18) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(297, 'city', '恩施土家族苗族自治州',18) ;
##19湖南省（2005年辖：13个地级市、1个自治州；34个市辖区、16个县级市、65个县、7个自治县。） ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(301, 'city', '长沙市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(302, 'city', '株洲市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(303, 'city', '湘潭市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(304, 'city', '衡阳市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(305, 'city', '邵阳市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(306, 'city', '岳阳市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(307, 'city', '常德市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(308, 'city', '张家界市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(309, 'city', '益阳市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(310, 'city', '郴州市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(311, 'city', '永州市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(312, 'city', '怀化市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(313, 'city', '娄底市',19) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(314, 'city', '湘西土家族苗族自治州',19) ;
##20广东省（截至2005年12月31日，广东省辖：21个地级市，54个市辖区、23个县级市、41个县、3个自治县，429个街道办事处、1145个镇、4个乡、7个民族乡。） ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(321, 'city', '广州市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(322, 'city', '深圳市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(323, 'city', '珠海市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(324, 'city', '汕头市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(325, 'city', '韶关市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(326, 'city', '佛山市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(327, 'city', '江门市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(328, 'city', '湛江市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(329, 'city', '茂名市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(330, 'city', '肇庆市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(331, 'city', '惠州市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(332, 'city', '梅州市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(333, 'city', '汕尾市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(334, 'city', '河源市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(335, 'city', '阳江市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(336, 'city', '清远市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(337, 'city', '东莞市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(338, 'city', '中山市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(339, 'city', '潮州市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(340, 'city', '揭阳市',20) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(341, 'city', '云浮市',20) ;
##21甘肃省（2006年辖：12个地级市、2个自治州；17个市辖区、4个县级市、58个县、7个自治县。） ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(351, 'city', '兰州市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(352, 'city', '金昌市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(353, 'city', '白银市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(354, 'city', '天水市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(355, 'city', '嘉峪关市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(356, 'city', '武威市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(357, 'city', '张掖市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(358, 'city', '平凉市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(359, 'city', '酒泉市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(360, 'city', '庆阳市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(361, 'city', '定西市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(362, 'city', '陇南市',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(363, 'city', '临夏回族自治州',21) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(364, 'city', '甘南藏族自治州',21) ;
##22四川省（2006年辖：18个地级市、3个自治州；43个市辖区、14个县级市、120个县、4个自治县。） ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(371, 'city', '成都市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(372, 'city', '自贡市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(373, 'city', '攀枝花市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(374, 'city', '泸州市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(375, 'city', '德阳市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(376, 'city', '绵阳市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(377, 'city', '广元市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(378, 'city', '遂宁市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(379, 'city', '内江市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(380, 'city', '乐山市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(381, 'city', '南充市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(382, 'city', '眉山市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(383, 'city', '宜宾市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(384, 'city', '广安市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(385, 'city', '达州市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(386, 'city', '雅安市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(387, 'city', '巴中市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(388, 'city', '资阳市',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(389, 'city', '阿坝藏族羌族自治州',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(390, 'city', '甘孜藏族自治州',22) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(391, 'city', '凉山彝族自治州',22) ;
##23贵州省(2006年辖：4个地级市、2个地区、3个自治州；10个市辖区、9个县级市、56个县、11个自治县、2个特区。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(401, 'city', '贵阳市',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(402, 'city', '六盘水市',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(403, 'city', '遵义市',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(404, 'city', '安顺市',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(405, 'city', '铜仁地区',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(406, 'city', '毕节地区',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(407, 'city', '黔西南布依族苗族自治州',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(408, 'city', '黔东南苗族侗族自治州',23) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(409, 'city', '黔南布依族苗族自治州',23) ;
##24海南省(2003－2005年　全省有2个地级市，6个县级市，4个县，6个民族自治县，4个市辖区，1个办事处（西南中沙群岛办事处，县级）。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(411, 'city', '海口市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(412, 'city', '三亚市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(413, 'city', '五指山市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(414, 'city', '琼海市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(415, 'city', '儋州市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(416, 'city', '文昌市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(417, 'city', '万宁市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(418, 'city', '东方市',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(419, 'city', '澄迈县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(420, 'city', '定安县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(421, 'city', '屯昌县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(422, 'city', '临高县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(423, 'city', '白沙黎族自治县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(424, 'city', '昌江黎族自治县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(425, 'city', '乐东黎族自治县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(426, 'city', '陵水黎族自治县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(427, 'city', '保亭黎族苗族自治县',24) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(428, 'city', '琼中黎族苗族自治县',24);
##25云南省(2006年辖：8个地级市、8个自治州；12个市辖区、9个县级市、79个县、29个自治县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(431, 'city', '昆明市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(432, 'city', '曲靖市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(433, 'city', '玉溪市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(434, 'city', '保山市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(435, 'city', '昭通市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(436, 'city', '丽江市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(437, 'city', '思茅市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(438, 'city', '临沧市',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(439, 'city', '文山壮族苗族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(440, 'city', '红河哈尼族彝族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(441, 'city', '西双版纳傣族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(442, 'city', '楚雄彝族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(443, 'city', '大理白族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(444, 'city', '德宏傣族景颇族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(445, 'city', '怒江傈傈族自治州',25) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(446, 'city', '迪庆藏族自治州',25) ;
##26青海省(2006年辖：1个地级市、1个地区、6个自治州；4个市辖区、2个县级市、30个县、7个自治县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(451, 'city', '西宁市',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(452, 'city', '海东地区',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(453, 'city', '海北藏族自治州',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(454, 'city', '黄南藏族自治州',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(455, 'city', '海南藏族自治州',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(456, 'city', '果洛藏族自治州',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(457, 'city', '玉树藏族自治州',26) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(458, 'city', '海西蒙古族藏族自治州',26) ;
##27陕西省(2006年辖：10个地级市；24个市辖区、3个县级市、80个县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(461, 'city', '西安市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(462, 'city', '铜川市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(463, 'city', '宝鸡市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(464, 'city', '咸阳市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(465, 'city', '渭南市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(466, 'city', '延安市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(467, 'city', '汉中市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(468, 'city', '榆林市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(469, 'city', '安康市',27) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(470, 'city', '商洛市',27) ;
##28广西壮族自治区(2005年辖：14个地级市；34个市辖区、7个县级市、56个县、12个自治县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(471, 'city', '南宁市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(472, 'city', '柳州市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(473, 'city', '桂林市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(474, 'city', '梧州市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(475, 'city', '北海市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(476, 'city', '防城港市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(477, 'city', '钦州市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(478, 'city', '贵港市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(479, 'city', '玉林市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(480, 'city', '百色市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(481, 'city', '贺州市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(482, 'city', '河池市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(483, 'city', '来宾市',28) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(484, 'city', '崇左市',28) ;
##29西藏自治区(2005年辖：1个地级市、6个地区；1个市辖区、1个县级市、71个县。) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(491, 'city', '拉萨市',29) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(492, 'city', '那曲地区',29) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(493, 'city', '昌都地区',29) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(494, 'city', '山南地区',29) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(495, 'city', '日喀则地区',29) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(496, 'city', '阿里地区',29) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(497, 'city', '林芝地区',29) ;
##30宁夏回族自治区 ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(501, 'city', '银川市',30) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(502, 'city', '石嘴山市',30) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(503, 'city', '吴忠市',30) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(504, 'city', '固原市',30) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(505, 'city', '中卫市',30) ;
##31新疆维吾尔自治区(2005年辖：2个地级市、7个地区、5个自治州；11个市辖区、20个县级市、62个县、6个自治县) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(511, 'city', '乌鲁木齐市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(512, 'city', '克拉玛依市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(513, 'city', '石河子市　',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(514, 'city', '阿拉尔市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(515, 'city', '图木舒克市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(516, 'city', '五家渠市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(517, 'city', '吐鲁番市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(518, 'city', '阿克苏市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(519, 'city', '喀什市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(520, 'city', '哈密市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(521, 'city', '和田市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(522, 'city', '阿图什市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(523, 'city', '库尔勒市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(524, 'city', '昌吉市　',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(525, 'city', '阜康市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(526, 'city', '米泉市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(527, 'city', '博乐市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(528, 'city', '伊宁市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(529, 'city', '奎屯市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(530, 'city', '塔城市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(531, 'city', '乌苏市',31) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(532, 'city', '阿勒泰市',31) ;
##32内蒙古自治区(2006年，辖：9个地级市、3个盟；21个市辖区、11个县级市、17个县、49个旗、3个自治旗。);
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(541, 'city', '呼和浩特市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(542, 'city', '包头市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(543, 'city', '乌海市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(544, 'city', '赤峰市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(545, 'city', '通辽市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(546, 'city', '鄂尔多斯市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(547, 'city', '呼伦贝尔市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(548, 'city', '巴彦淖尔市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(549, 'city', '乌兰察布市',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(550, 'city', '锡林郭勒盟',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(551, 'city', '兴安盟',32) ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(552, 'city', '阿拉善盟',32) ;
##33澳门特别行政区 ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(561, 'city', '澳门特别行政区',33) ;
##34香港特别行政区 ;
INSERT IGNORE INTO dictionary(id, data_type, dictionary_value, dictionary_key) VALUES(571, 'city', '香港特别行政区',34) ;


