# Generated by Django 2.2.6 on 2019-10-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191023_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_scores',
            field=models.IntegerField(default=0),
        ),
    ]
