# Generated by Django 2.2.6 on 2019-10-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_p_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_big_pic',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_jd_skuid',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_promotion_url',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
