# Generated by Django 2.2.6 on 2019-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191024_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cid2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cid2Name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cid3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cid3Name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cidName',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_big_pic',
            field=models.CharField(default='no pic', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='no name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_promotion_url',
            field=models.CharField(default='no url', max_length=400),
        ),
    ]
